/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
public void Start(GButton source, GEvent event) { //_CODE_:Start_button:839361:
  source.setVisible(false);
  window1.setVisible(true);
  println("Start_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Start_button:839361:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:758463:
  appc.background(230);
} //_CODE_:window1:758463:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Start_button = new GButton(this, 220, 340, 160, 80);
  Start_button.setText("Strat");
  Start_button.addEventHandler(this, "Start");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 300, 600, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton Start_button; 
GWindow window1;
